### ISSUE TITLE
DC Invite

### ISSUE THREAD

**Issue by shawnlunsford** [agamsol/Discord-Stealer#3]
Not related to this specific project/repository, but would like to point out the invite on MrSSH is invalid (Cannot be used)

If possible, update it, so others don't have to lurk around your GitHub repositories for them lol

Also, since my other account has been Phone Locked, and my new account is barely a day old, is it possible to still join under this new account before Jan. 28th w/o getting kicked or nah?

**Comment by agamsol** [comment]
Joining the [discord server](discord.gg/ba3ymJ4nTw) Should work.
If there are any problems please contact me `Agam#0001`

### Also, I have successfully been updating the discord server's invite link..
